# Generated by Django 3.1.4 on 2020-12-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('director_name', models.CharField(max_length=100)),
                ('producer_name', models.CharField(max_length=100)),
                ('slug', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.FloatField()),
                ('hair_color', models.CharField(max_length=20)),
                ('eye_color', models.CharField(max_length=20)),
                ('slug', models.CharField(default='', max_length=64)),
                ('films', models.ManyToManyField(to='jpfilms.Film')),
            ],
        ),
    ]
