# Generated by Django 3.1.4 on 2020-12-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpfilms', '0002_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(max_length=70),
        ),
    ]
