# Generated by Django 3.1.4 on 2020-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpfilms', '0003_auto_20201203_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='external_reference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
