# Generated by Django 3.1.4 on 2020-12-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpfilms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
