# Generated by Django 3.1.4 on 2020-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpfilms', '0004_film_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='external_reference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
