# Generated by Django 3.1.4 on 2020-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpfilms', '0005_people_external_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='external_reference',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='people',
            name='external_reference',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
