# Generated by Django 3.1.4 on 2020-12-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpfilms', '0006_auto_20201206_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
