// Code generated by MockGen. DO NOT EDIT.
// Source: ../pbfilms/films.pb.go

// Package pbfilmstest is a generated GoMock package.
package pbfilmstest

import (
	gomock "github.com/golang/mock/gomock"
)
