version: "3"
services:
  frontend:
    build:
      context: frontend
    ports:
     - "8000:8000"

  films_db:
    env_file: backend/films/build/db/dev.env
    image: postgres@sha256:baf51b409ec8d7ee043bc33014e3c01ec06bcfbd0afa7b4cc5973fe56f46d09f
    volumes:
      - films_db:/var/lib/postgresql/data


  films_svc:
    env_file: backend/films/build/svc/dev.env
    build:
      context: backend/films
      args:
        svc_name: films
    ports:
      - "9990:9990"
      - "10000:10000"
    volumes:
      - ./backend/films/migrations:/films/migrations
    depends_on:
      - films_db

  ghibli_svc:
    env_file: backend/ghibli/build/svc/dev.env
    build:
      context: backend/ghibli
      args:
        svc_name: ghibli

volumes:
  films_db:
